-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.transactions
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "userId" integer NOT NULL,
    "typeOfTransaction" character varying COLLATE pg_catalog."default" NOT NULL,
    amount integer NOT NULL,
    "recipientId" integer,
    status character varying COLLATE pg_catalog."default" NOT NULL,
    currency character varying COLLATE pg_catalog."default" NOT NULL,
    gateway character varying COLLATE pg_catalog."default" NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    "transactionReference" character varying COLLATE pg_catalog."default" NOT NULL,
    otp character varying COLLATE pg_catalog."default",
    "secretKey" character varying COLLATE pg_catalog."default",
    "bankAccount" character varying COLLATE pg_catalog."default",
    bank character varying COLLATE pg_catalog."default",
    "nameOnAccount" character varying COLLATE pg_catalog."default",
    CONSTRAINT transactions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1001000100 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "firstName" character varying COLLATE pg_catalog."default" NOT NULL,
    "lastName" character varying COLLATE pg_catalog."default" NOT NULL,
    "createdAt" date NOT NULL,
    "updatedAt" date NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    balance integer NOT NULL,
    "isVerified" boolean NOT NULL,
    currency character varying COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT "recipientId" FOREIGN KEY ("recipientId")
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT "userId" FOREIGN KEY ("userId")
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;